[colors.primary]
foreground = "#ebdbb2"
background = "#282828"

[colors.normal]
black   = "#282828"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"

[colors.bright]
black   = "#928374"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

[font]
builtin_box_drawing = true
size = 11.0

[font.bold]
family = "Mononoki Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Mononoki Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Mononoki Nerd Font"
style = "Italic"

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"

[scrolling]
history = 10000

[window]
decorations = "none"
dynamic_padding = true

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 0
y = 0
