#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         5
bspc config window_gap           10

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc config normal_border_color "#282828"
bspc config active_border_color "#a89984"
bspc config focused_border_color "#a89984"

bspc rule -a Thunar state=floating rectangle=800x800+0+0 center=true
